const Corporate = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const TechBro = [
  'Mentions their TC',
  'Wears patagonia',
  'Owns Airpods',
  'Bought Dogecoin',
  'Wants to go to burning man',
  'Still waiting to vest their shares',
  'Watches the NBA',
  'Warby Parker glasses',
  'Dating profile mentions hiking',
  'Owns single-color hoodie',
  'Drives a Tesla',
  'Follows Elon Musk',
  'Traveled to a tech conference',
  'Works from home',
  'Flew to NYC in the past 6 months',
  'Churns credit cards',
  'Job feeds them most meals',
  'Wears allbirds',
  'has a fade',
  'Has dab pen',
  'Apple Watch',
  'Drinks white claw or la croix',
  'Likes IPAs',
  'Voted for Andrew Yang',
  'Listens to Joe Rogan',
  'Works (or wants to) at FAANG',
];

const Political = [
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];

const Karen = [
  'Threatens to call police',
  '"Stop Filming me"',
  'Threatens to sue',
  'Fake Laughs',
  'Is wearing pink',
  'Is wearing sweatpants',
  'Holding baby',
  'Asks for manager',
  'Is white',
  'Bob cut',
  'Angry',
  'Fake nice',
  'Shrieks',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];

const Weeb = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const Empty = [];

export const presetCategories = {
  Corporate,
  TechBro,
  Political,
  Karen,
  Weeb,
};
