const Corporate = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const TechBro = [
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'TEST',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const Political = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const Karen = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

const Weeb = [
  'Someone wearing patagonia',
  'Someone wearing allbirds',
  'Airpods or case visible',
  'RSUs mentioned',
  'Earnings report',
  'Vest and rest',
  '1 billion in the bank',
  'Swimply',
  'Circle back',
  'Presentation of more than 40 slides',
  'Catered Food',
  'CEO high fives someone',
  'Apple watch',
  'Mandarin spoken',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Revenue Forecast',
  'Any or Q1, Q2, Q3,Q4',
  'Acronym with more than 4 lettersa',
  'Acronym with more than 4 lettersa',
  'More than 3 acronyms in one sentence',
];

export const presetCategories = {
  Corporate,
  TechBro,
  Political,
  Karen,
  Weeb,
};
