import { Category } from './types';

// done
const Corporate: Category = {
  squares: [
    'Someone wearing patagonia',
    'Someone wearing allbirds',
    'Airpods or case visible',
    'RSUs mentioned',
    'Earnings report',
    'Vest and rest',
    '1 billion in the bank',
    'Swimply',
    'Circle back',
    'Presentation of more than 40 slides',
    'Catered Food',
    'CEO high fives someone',
    'Apple watch',
    'Mandarin spoken',
    'Revenue Forecast',
    'Revenue Forecast',
    'Revenue Forecast',
    'Revenue Forecast',
    'Revenue Forecast',
    'Revenue Forecast',
    'Revenue Forecast',
    'Any or Q1, Q2, Q3,Q4',
    'Acronym with more than 4 lettersa',
    'Acronym with more than 4 lettersa',
    'More than 3 acronyms in one sentence',
  ],
  freeParking: 'FREE TESLA PARKING',
};

// done
const TechBro: Category = {
  squares: [
    'Mentions their TC',
    'Wears patagonia',
    'Owns Airpods',
    'Bought Dogecoin',
    'Wants to go to burning man',
    'Still waiting to vest their shares',
    'Watches the NBA',
    'Warby Parker glasses',
    'Dating profile mentions hiking',
    'Owns single-color hoodie',
    'Drives a Tesla',
    'Follows Elon Musk',
    'Traveled to a tech conference',
    'Works from home',
    'Flew to NYC in the past 6 months',
    'Churns credit cards',
    'Job feeds them most meals',
    'Wears allbirds',
    'has a fade',
    'Has dab pen',
    'Apple Watch',
    'Drinks white claw or la croix',
    'Likes IPAs',
    'Voted for Andrew Yang',
    'Listens to Joe Rogan',
    'Works (or wants to) at FAANG',
  ],
  freeParking: 'FREE PARKING: Leetcode Account',
};

const FinanceBro: Category = {
  squares: [],
  freeParking: 'FREE PARKING: Member of WSB',
};

const FratBro: Category = {
  squares: [],
  freeParking: 'FREE PARKING: Shotgunned Beer',
};

const C3: Category = {
  squares: [],
  freeParking: 'FREE PARKING: Shotgunned Beer',
};

// done
const ABG: Category = {
  squares: [
    'Likes Boba',
    'Likes to Rave',
    'Has tattoo(s)',
    'Fake eyelashes',
    'Duck Face Selfie',
    "Goes to Dave & Buster's",
    'Cries to Illenium',
    'Toxic Relationship',
    '"Shoulder Ride"',
    'Attracted to red flags',
    'Stuffed animal backpack',
    'Drinks Hennessy',
    'Dyed Hair',
    'Photo with sports car',
    'Goes to San Jose State or UC system',
    'Went to Coachella',
    'Rolled on a weekday',
    'In Asian sorority or FSA',
    'Boyfriend also has tattoo',
    'Dab Pen',
    'Vapes',
    'Female',
    'Says "Starbies"',
    'Has made Kandi',
    'Pigtails or braids',
  ],
  freeParking: 'FREE PARKING: Asian',
};

const JehovahsWitness: Category = {
  squares: [],
  freeParking: '',
};

const Politician: Category = {
  squares: [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  freeParking: '',
};

const Karen: Category = {
  squares: [
    'Threatens to call police',
    '"Stop Filming me"',
    'Threatens to sue',
    'Fake Laughs',
    'Is wearing pink',
    'Is wearing sweatpants',
    'Holding baby',
    'Asks for manager',
    'Is white',
    'Bob cut',
    'Angry',
    'Fake nice',
    'Shrieks',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  freeParking: '',
};

const Weeb: Category = {
  squares: [
    'Says "Naruhodo"',
    'Wants to go to Japan',
    'Says "Waifu"',
    'Wants to go to Comic Con',
    '"The manga is better"',
    'Lives with parents',
    'Owned a fedora',
    '"I\'m learning Japanese"',
    'Plays Pokemon Go',
    'Has crunchyroll account',
    'Anime Theme Music playlist',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  freeParking: 'FREE PARKING: Watches anime',
};

const Empty: Category = { squares: [], freeParking: '' };

export const presetCategories = {
  Corporate,
  TechBro,
  Political: Politician,
  Karen,
  Weeb,
  FinanceBro,
  FratBro,
  JehovahsWitness,
  ABG,
  C3,
};

export const emptyCellStates = [
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
];
