import { Category } from './types';

// done
const Corporate: Category = {
  squares: [
    'Someone wearing patagonia',
    'Someone wearing allbirds',
    'Airpods or case visible',
    'RSUs mentioned',
    'Earnings report',
    'Vest and rest',
    '1 billion in the bank',
    'Circle back',
    'Presentation of more than 40 slides',
    'Catered Food',
    'Software Engineer wearing shorts',
    'Sales Person in suit',
    'CEO high fives someone',
    'Apple watch',
    'Mandarin spoken',
    'Revenue Forecast',
    'Any or Q1, Q2, Q3, Q4',
    'Acronym with more than 4 letters',
    'More than 3 acronyms in one sentence',
    'Meeting runs over time',
    'Meeting of over 30 people',
    'Weekly Happy Hour',
    'Team Morale Mentioned',
    'Someone says "Forecast"',
    'Stock Price mentioned',
    'Level Best',
    'PTO',
  ],
  freeParking: 'FREE PARKING: Excel on a Resume',
};

// done
const TechBro: Category = {
  squares: [
    'Mentions their TC',
    'Wears patagonia',
    'Owns Airpods',
    'Bought Dogecoin',
    'Wants to go to burning man',
    'Still waiting to vest their shares',
    'Watches the NBA',
    'Warby Parker glasses',
    'Dating profile mentions hiking',
    'Owns single-color hoodie',
    'Drives a Tesla',
    'Follows Elon Musk',
    'Traveled to a tech conference',
    'Works from home',
    'Flew to NYC in the past 6 months',
    'Churns credit cards',
    'Job feeds them most meals',
    'Wears allbirds',
    'has a fade',
    'Has dab pen',
    'Apple Watch',
    'Drinks white claw or la croix',
    'Likes IPAs',
    'Voted for Andrew Yang',
    'Listens to Joe Rogan',
    'Works (or wants to) at FAANG',
  ],
  freeParking: 'FREE PARKING: Leetcode Account',
};

const FinanceBro: Category = {
  squares: [
    'Lives in NYC',
    'Wants to be VC, PE or IB',
    "Didn't beat the market",
    'Tweets about their favorite stock',
    'Sells covered calls',
    'Churns credit cards',
    'Loves to talk about credit cards',
    'Main goal is to get rich',
    'Trades cryptocurrency',
    'Wears vest',
    'Favorite movie The Wolf of Wall Street',
    'Favorite Movie The Big Short',
    'Works/wants to at Goldman Sachs',
    'At least 2 coffees per day',
    'Owns trench coat',
    "Doesn't go above 86th",
    'Stocks are main personality trait',
    'Brown Dress shoes or loafers',
    'LinkedIn is favorite website',
    'Robinhood account',
    'Apple Watch',
    'Member of WSB',
    'Patagonia',
    'Shops at J-Crew',
    '"I prefer metal credit cards"',
    'Tells you how much they make',
    'Vaguely Republican',
  ],
  freeParking: 'FREE PARKING: Works in Finance',
};

// done
const FratBro: Category = {
  squares: [
    'Owns Cowboy Boots',
    'Wears Frockets',
    'Plaid jacket',
    'In a fantasy football league',
    'Trains for intramural sports',
    'Rich Parents',
    'Only listens to rap',
    'Goes out in sports jerseys',
    'Sports jersey = Halloween costume',
    'Works out biceps',
    'Spring Break in Florida',
    'Attempted to jump through at least one table',
    'Ping pong balls are for beer pong',
    'Vapes',
    'Wears Baseball Cap',
    'Wears sunglasses indoors',
    'Primary Color shorts',
    'High black or white socks',
    'Studying Business',
    'Listens to Joe Rogan',
    'Drives Lofted Truck',
    'Airpods in during conversation',
    'Watches/Listens to alpha male influencers',
    'Owns dab pen',
    'Only works out sleeveless',
    'Follows barstool sports',
  ],
  freeParking: 'FREE PARKING: Shotgunned Beer',
};

// done
const C3: Category = {
  squares: [
    'Someone wearing patagonia',
    'Someone wearing allbirds',
    'Airpods or case visible',
    'RSUs mentioned',
    'Earnings report',
    'Vest and rest',
    '1 billion in the bank',
    'Circle back',
    'Presentation of more than 40 slides',
    'Catered Food',
    'Software Engineer wearing shorts',
    'Sales Person in suit',
    'Apple watch',
    'Mandarin spoken',
    'Revenue Forecast',
    'Any of Q1, Q2, Q3, Q4',
    'Acronym with more than 4 letters',
    'More than 3 acronyms in one sentence',
    'Meeting runs over time',
    'Meeting of over 30 people',
    'Weekly Happy Hour',
    'Team Morale Mentioned',
    'Someone says "Forecast"',
    'Stock Price mentioned',
    'Level Best',
    'PTO',
    'Palantir',
    'SDL mentioned',
    'New v8 bug',
    'UI Designer Mentioned',
    '"Killer Sales Team"',
    'Engineer caught taking extra snacks',
    'Jenkins, Github or Jira is down',
    'TS spotted in the bathroom',
  ],
  freeParking: 'FREE PARKING: Knows what TS means',
};

// done
const OrthoBro: Category = {
  squares: ['ANCEF', 'Buff af', 'Says bro a lot', 'Owns airpods'],
  freeParking: 'FREE PARKING: A',
};

// done
const ABG: Category = {
  squares: [
    'Likes Boba',
    'Has tattoo(s)',
    'Fake eyelashes',
    'Duck Face Selfie',
    "Goes to Dave & Buster's",
    'Cries to Illenium',
    'Toxic Relationship',
    '"Shoulder Ride"',
    'Attracted to red flags',
    'Stuffed animal backpack',
    'Drinks Hennessy',
    'Dyed Hair',
    'Photo with sports car',
    'Goes to San Jose State or UC system',
    'Went to Coachella',
    'Rolled on a weekday',
    'In Asian sorority or FSA',
    'SO also has tattoo',
    'Dab Pen',
    'Vapes',
    '"My Tolerance is high"',
    'Has made Kandi',
    'Air Force Ones',
    'Pigtails or braids',
    'Met best friend at a rave',
  ],
  freeParking: 'FREE PARKING: Likes to Rave',
};

// done
const Weeb: Category = {
  squares: [
    'Says "Naruhodo"',
    'Wants to go to Japan',
    'Says "Waifu"',
    'Wants to go to Comic Con',
    '"The manga is better"',
    'Owned a fedora',
    '"I\'m learning Japanese"',
    'Plays Pokemon Go',
    'Has crunchyroll account',
    'Studies to Anime Theme Music',
    'Rates every anime 10/10',
    'In anime discord server',
    'Anime character as phone background',
    'Anime character as profile picture',
    'Favorite movie is studio ghibli',
    'Runs like Naruto',
    'Cosplay',
    'Says "Arigato"',
    'Owns a kimono',
    'Owns a katana',
    'Favorite meal is ramen',
    'Attracted to pink hair',
    'Read Shonen Jump',
    'Owns Pokemon cards',
    'Owns Yu-gi-oh cards',
  ],
  freeParking: 'FREE PARKING: Watches anime',
};

export const presetCategories = {
  Corporate,
  'Tech Bro': TechBro,
  Weeb,
  'Finance Bro': FinanceBro,
  'Frat Bro': FratBro,
  ABG,
  'C3.ai': C3,
};

export const emptyCellStates = [
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
  { isClicked: false },
];
